### ISSUE TITLE
How to use this example with Mbed Studio

### ISSUE THREAD

**Issue by wemaxon** [micro-ROS/micro_ros_mbed#11]
- Hardware description:  [SparkFun LoRa Thing Plus](https://www.sparkfun.com/products/17506) 
- RTOS:  mbed-os  6.11 or 6.10
- Version or commit hash: foxy 

Hi, I'd like to use micro-ros and the Micro XRCE-DDS Architecture to transmit data via serial. I am using the  [SparkFun LoRa Thing Plus](https://www.sparkfun.com/products/17506) Board which is supported by mbed-os. What would be the best Workflow to get this example to compile and run using Mbed Studio?

This is what I did so far: I importedt this repository as a project to Mbed Studio. The example wouldn't compile and i realised, that all of the included librarys were missing. Therefore I imported the following repositories to my project as well: rcl, rclc, rcutils, rmw, rmw-microxrcedds and tried to compile. This didnt work, I tried it with mbed-os 6.11 and 6.10. 
This is the output when compiling (mbed-os 6.10)

```
Building project micro_ros_mbed (SFE_ARTEMIS_THING_PLUS, ARMC6)
Scan: micro_ros_mbed
Configuration error: Bootloader not supported on this target. ROM start not found in targets.json.
Configuration error: Bootloader not supported on this target. RAM start not found in targets.json.
Compile [  0.1%]: RTX_Config.c
Compile [  0.2%]: cmsis_os1.c
Compile [  0.2%]: rtx_delay.c
Compile [  0.3%]: rtx_evr.c
Compile [  0.4%]: rtx_lib.c
Compile [  0.5%]: irq_cm4f.S
Compile [  0.5%]: rtx_evflags.c
Compile [  0.6%]: rtx_memory.c
Compile [  0.7%]: rtx_kernel.c
Compile [  0.8%]: rtx_mempool.c
Compile [  0.9%]: rtx_msgqueue.c
Compile [  0.9%]: rtx_mutex.c
Compile [  1.0%]: mbed_tz_context.c
Compile [  1.1%]: rtx_semaphore.c
Compile [  1.2%]: rtx_system.c
Compile [  1.2%]: os_systick.c
Compile [  1.3%]: rtx_timer.c
Compile [  1.4%]: os_tick_ptim.c
Compile [  1.5%]: mbed_boot_arm_std.c
Compile [  1.5%]: rtx_thread.c
Compile [  1.6%]: hci_cmd_bis.c
Compile [  1.7%]: hci_cmd_cis.c
Compile [  1.8%]: mbed_rtos_rtx.c
[Error] mbed_retarget.h@515,5: unknown type name 'time_t'; did you mean 'size_t'?
[Error] mbed_retarget.h@516,5: unknown type name 'time_t'; did you mean 'size_t'?
[Error] mbed_retarget.h@517,5: unknown type name 'time_t'; did you mean 'size_t'?
[ERROR] In file included from .\mbed-os\cmsis\device\rtos\source\mbed_rtos_rtx.c:23:
In file included from ./mbed-os/platform/include/platform\mbed_error.h:21:
./mbed-os/platform/include\platform/mbed_retarget.h:515:5: error: unknown type name 'time_t'; did you mean 'size_t'?
time_t    st_atime;   ///< Time of last access
^~~~~~
size_t
c:\ProgramData\Mbed Studio\mbed-studio-tools\ac6\bin\..\include\string.h:44:26: note: 'size_t' declared here
typedef unsigned int size_t;   /* see <stddef.h> */
^
In file included from .\mbed-os\cmsis\device\rtos\source\mbed_rtos_rtx.c:23:
In file included from ./mbed-os/platform/include/platform\mbed_error.h:21:
./mbed-os/platform/include\platform/mbed_retarget.h:516:5: error: unknown type name 'time_t'; did you mean 'size_t'?
time_t    st_mtime;   ///< Time of last data modification
^~~~~~
size_t
c:\ProgramData\Mbed Studio\mbed-studio-tools\ac6\bin\..\include\string.h:44:26: note: 'size_t' declared here
typedef unsigned int size_t;   /* see <stddef.h> */
^
In file included from .\mbed-os\cmsis\device\rtos\source\mbed_rtos_rtx.c:23:
In file included from ./mbed-os/platform/include/platform\mbed_error.h:21:
./mbed-os/platform/include\platform/mbed_retarget.h:517:5: error: unknown type name 'time_t'; did you mean 'size_t'?
time_t    st_ctime;   ///< Time of last status change
^~~~~~
size_t
c:\ProgramData\Mbed Studio\mbed-studio-tools\ac6\bin\..\include\string.h:44:26: note: 'size_t' declared here
typedef unsigned int size_t;   /* see <stddef.h> */
^
3 errors ge
```

Do I need colcon to compile this example? Why is that, why couldn't I compile the example with the compiler included in Mbed Studio ? Is this possible on my windows machine?

Thanks for your help!

**Comment by pablogs9** [comment]
Hi, this package is intended to be used with [Mbed CLI 2](https://os.mbed.com/docs/mbed-os/v6.11/build-tools/install-or-upgrade.html), instructions for using it are [here](https://github.com/micro-ROS/micro_ros_mbed#example). 

Support for Mbed Studio is not currently planned. But you always can prepare a [custom micro-ROS library](https://micro.ros.org/docs/tutorials/advanced/create_custom_static_library/) build and integrate it as a static library in your toolchain.

Colcon is needed because ROS 2 packages need this meta-build-system tool to be compiled, so micro-ROS also need it. But this is not a compiler, colcon will use the compiler specified in the toolchain.

Finally, micro-ROS is only fully supported under Linux.

Let us know if you need further guidance with the library generation for your platform.

**Comment by wemaxon** [comment]
Hey @pablogs9,

thanks again for your prompt support!

I have run into some issues while creating my static library. I have created an issure [here](https://github.com/micro-ROS/micro_ros_setup/issues/338), I hope this was the right place.
