### ISSUE TITLE
No functionality with Nucleo F446RE

### ISSUE THREAD

**Issue by ankbhatia19** [micro-ROS/micro_ros_mbed#30]
- Hardware description: Nucleo F446RE (https://os.mbed.com/platforms/ST-Nucleo-F446RE/)
- RTOS: mbed
- Installation type: From source
- Version or commit hash: Latest version from master branch

#### Steps to reproduce the issue
1. `mbed-tools import https://github.com/micro-ROS/micro_ros_mbed.git`
2. `mbed-tools deploy`
3. `mbed-tools compile -m NUCLEO_F446RE -t GCC_ARM -f --sterm`
4. Run micro-ros-agent with: `docker run -it --rm -v /dev:/dev -v /dev/shm:/dev/shm --privileged --net=host microros/micro-ros-agent:galactic serial --dev /dev/ttyACM0 -v6`

Added a few print statements to diagnose issue:

![Screenshot from 2022-04-23 15-59-23](https://user-images.githubusercontent.com/25870725/164948969-dd89d60a-4ac8-42da-8837-3ac9adbd185f.png)

#### Expected behavior
- Expect to see LED1 blinking every 100ms, indicating functionality
- Expect publisher and mbed node to be displayed (via `ros2 topic list` and `ros2 node list`) after runinng micro-ros agent

#### Actual behavior
- No LED blinking
- Various strange characters in serial output, as shown below
![Screenshot from 2022-04-23 15-58-47](https://user-images.githubusercontent.com/25870725/164948945-c4809570-0f71-4c01-b12b-c87a4bec9fc1.png)
- "Finished support init..." message is never reached
- micro-ros-agent receives no new messages, and there are no new topics published as well as no node created

#### Additional information
Have added print statements to find the problem line, and have narrowed it down to the rclc_support_init() call on line 52. Program never seems to move past this function call.

**Comment by pablogs9** [comment]
Please try to not open a serial port twice. If you are connecting the micro-ROS client to the agent using a serial port, avoid opening the same serial port on another console.

Also, are those printf being printed in the same serial port that micro-ROS uses?

**Comment by ankbhatia19** [comment]
Even when running without `—sterm` flag on `mbed compile`, the issue persists. I have also commented out the `printf` calls for the time being, until I add another serial port for debugging

**Comment by pablogs9** [comment]
Can you share the output of the micro-ROS Agent using the flag `-v6`?

**Comment by ankbhatia19** [comment]
![Screenshot from 2022-04-26 19-40-47](https://user-images.githubusercontent.com/25870725/165429040-ceddde3b-ef42-47a6-a917-5a20cbb689bd.png)

Doesn't appear to be seeing much...

**Comment by ankbhatia19** [comment]
Earlier, I failed to mention that my `mbed` environment is running inside a docker container. I was able to solve this issue by flashing the Nucleo using the `mbed` container, killing the container, then pressing the Reset button on the Nucleo. At this point I could safely run the `micro-ros-agent` and see the correct output.

**Comment by supercrazysam** [comment]
sorry to ask here, I am trying to do basically the same thing. @pablogs9 

For step 4) mentioned above, Is it possible to run micro-ros-agent natively on 22.04 without docker?  
Please provide more details on how to make it work this way,  thank you so much!!

================   
From the pieces of information I saw by google search, heres what I have gathered so far...  
e.g.  after the compile and flash step,  do I just do:  

**Creating the micro-ROS agent**
`ros2 run micro_ros_setup create_agent_ws.sh`  
`ros2 run micro_ros_setup build_agent.sh`
`source install/local_setup.bash`

**Running the micro-ROS app**   
`ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0 -v6`  

And then all the topics from the stm32 will be able to send/receive rostopic with upstream computer?
