### ISSUE TITLE
WiKi - Creating a communication between STM32 using Mbed OS and PC through micro ROS

### ISSUE THREAD

**Issue by htex0189** [micro-ROS/micro_ros_mbed#33]
Hi

Please I would like to get some guidance for creating this project, send and receive ros2 topics between STM32 micro controller running mbed OS and x86 PC running ROS2.

Thanks,

**Comment by pablogs9** [comment]
Which problems have you had building and using the example: https://github.com/micro-ROS/micro_ros_mbed#example ?

**Comment by htex0189** [comment]
I am not clear with what to start with for initializing micro ros library in the mbed studio project that is using mbed os 6.

**Comment by pablogs9** [comment]
Do you have a ready to use project using (mbed CLI 2](https://os.mbed.com/docs/mbed-os/v6.15/build-tools/mbed-cli-2.html), once it is ready, building this repo is straightforward

**Comment by htex0189** [comment]
Thanks it works
