### ISSUE TITLE
Creating Multiple publisher

### ISSUE THREAD

**Issue by htex0189** [micro-ROS/micro_ros_mbed#34]
Hi,

I run the example with one publisher and it is working. I can read the message with micro_ros agent.
But when adding another publisher, the new publisher is not registered with micro_ros agent. rclc_publisher_init_default returns error at second publisher.

So How to create multiple publisher. And is it necessary to use executors with timer to publish or publish messages directly without using executors?

Thanks

**Comment by htex0189** [comment]
Is the meta config for rmw_microxrcedds for mbed is not yet developed to configure max publisher,subscriber,node for mbed?

**Comment by htex0189** [comment]
I changed the colcon meta config - increased the number of publisher subscribers. I still cannot create two publisher. Please could you tell what should be done after changing colcon meta file

**Comment by htex0189** [comment]
After correct building It works.

**Comment by AjinJayan** [comment]
Thanks that was really helpful
