### ISSUE TITLE
Agent produces DDS error 

### ISSUE THREAD

**Issue by spartacoos** [micro-ROS/micro_ros_mbed#9]
## Agent produces DDS error + mbed board does not appear in node list

- Hardware description: [ST B-L475E-IOT01A Discovery kit](https://www.st.com/en/evaluation-tools/b-l475e-iot01a.html) running the [publisher example](https://github.com/micro-ROS/micro_ros_mbed/blob/main/main.cpp) connected to a [Dell Inspiron 13 Laptop](https://www.dell.com/en-uk/work/shop/laptop-computers-for-businesses/inspiron-13/spd/inspiron-13-5301-laptop/bn53105?SID=CjwKCAjwtJ2FBhAuEiwAIKu19laUwERte8MzWJ0a4SaMSuuIqwypvV33b90RdVPka823y8WgoSgf1BoCqPgQAvD_BwE) running Ubuntu 20.04.
- RTOS: [Mbed OS](https://os.mbed.com/mbed-os/) with [CLI2](https://os.mbed.com/docs/mbed-os/v6.10/build-tools/mbed-cli-2.html)
- Installation type: as seen [here](https://github.com/micro-ROS/micro_ros_mbed) also tried with this [agent](https://github.com/eProsima/Micro-XRCE-DDS-Agent) and this [one](https://snapcraft.io/micro-ros-agent).
- Version or commit hash: ROS2 foxy, hash -> f702c68500cd48d506c36016bf209869cbae8c80

#### Steps to reproduce the issue
1.Install ROS2 on your system (Ubuntu 20.04) by following [these steps](https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Binary.html). 
2. Install [Mbed CLI2](https://os.mbed.com/docs/mbed-os/v6.10/build-tools/mbed-cli-2.html), the project [dependencies](https://github.com/micro-ROS/micro_ros_mbed#Dependencies) and compile [this example](https://github.com/micro-ROS/micro_ros_mbed#Example) onto the board.
3.  Open a terminal, compile (using colcon) and run [this Python listener](https://github.com/micro-ROS/micro_ros_mbed/files/6523499/subscriber_member_function.zip) which subscribes to "mbed_int32_publisher".
4. Open another terminal, run the agent `sudo ./MicroXRCEAgent serial --dev /dev/ttyACM0 -v6`

#### Actual behavior
**DDS error:**
![Screenshot from 2021-05-21 11-59-17](https://user-images.githubusercontent.com/29025235/119159967-b2360700-ba4f-11eb-9a55-ce02d6b7a50b.png)

#### Expected behavior
**From the Portenta example**
By simply using the portenta instead and changing the topic name to "micro_ros_arduino_node_publisher" on the [listener](https://github.com/micro-ROS/micro_ros_mbed/files/6523499/subscriber_member_function.zip) script we get the correct output on the top right terminal:
![Screenshot from 2021-05-21 15-24-00](https://user-images.githubusercontent.com/29025235/119160272-f923fc80-ba4f-11eb-9ae3-6a5c835bd38e.png)

#### Additional information
I tried with both the [Micro-XRCE agent](https://github.com/eProsima/Micro-XRCE-DDS) (as seen above) and with the [micro-ros-agent](https://snapcraft.io/micro-ros-agent) used as seen [here](https://ubuntu.com/blog/getting-started-with-micro-ros-on-raspberry-pi-pico) but with "snapd:st-linkv21" instead of "snapd:pico.

**Comment by Acuadros95** [comment]
Hello @spartacoos, Which agent branch are you using for the [Micro-XRCE agent](https://github.com/eProsima/Micro-XRCE-DDS-Agentl)?

The snap agent version needs to be updated to fix this problem, could you try with the dockerized version?

`docker run -it --rm --net=host -v /dev:/dev -v /dev/shm:/dev/shm --privileged microros/micro-ros-agent:foxy serial --dev /dev/ttyACM0 -v6`

**Comment by spartacoos** [comment]
Hi @Acuadros95, I just tried with your approach and this makes it so that on the agent side there are no dds errors. However, the listener still can't receive the messages. Oddly enough, If I run `ros2 node list` I get an empty output. If I run `ros2 topic list` I only get "

```
/parameter_events
/rosout
```
but if I try to publish to it by running ```ros2 topic pub /mbed_int32_publisher std_msgs/msg/Int32 "data: 1"``` this works and the listener publishes I heard "1". Any idea what the issue could be here? It seems to me like the listener and publisher are not being discovered.

**Comment by spartacoos** [comment]
Also, if I try to run `ros2 topic pub /mbed_int32_publisher std_msgs/msg/Int32 "data: 1"` while the agent is running this makes it so that the listener doesn't output anything. If I try when the agent is not running then it works.

**Comment by Acuadros95** [comment]
I can't replicate that issue on my computer, looks like a communication problem with the dockerized agent.

You can also try to recompile the agent, making sure you are using the latest version and then running it like on your first post: `sudo ./MicroXRCEAgent serial --dev /dev/ttyACM0 -v6`

Just make sure you build the latest commit from the [foxy](https://github.com/eProsima/Micro-XRCE-DDS-Agent/tree/foxy) branch.

**Comment by spartacoos** [comment]
Fantastic! Thank you @Acuadros95, that seems to have worked!
